# Generated by Django 3.2.3 on 2021-06-05 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test_stat',
            fields=[
                ('test_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('score', models.IntegerField()),
                ('subject', models.CharField(max_length=20)),
            ],
        ),
    ]
